FROM golang:1.7.3 as builder
WORKDIR /go/src/
RUN go get -d -v golang.org/x/net/html
COPY app.go	.
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /go/src/app .
CMD ["./app"]
